#!/bin/bash

MacOSDir=$(cd -P -- "$(dirname -- "$0")" && printf '%s\n' "$(pwd -P)")
script=${MacOSDir}/TestApp.py
export ContentsDir="$(dirname -- "$MacOSDir")"
exec /opt/miniconda/miniconda3/envs/pyqt5/bin/python $script "$@"
